### Obtener todos los usuarios
GET http://localhost:4001/api/productos
Content-Type: application/json
x-auth-token: <tu_token_aqui>

###
GET http://localhost:4001/api/productos/66bbc64ec5d07458e5610223
Content-Type: application/json
x-auth-token: <tu_token_aqui>

###

PATCH http://localhost:4001/api/productos/66bbcea52f596d56a7786cb1/estado
Content-Type: application/json
x-auth-token: <tu_token_aqui>

{
  "estado": "inactivo"
}

###

PATCH http://localhost:4001/api/productos/66bbcea52f596d56a7786cb1/stock
Content-Type: application/json
x-auth-token: <tu_token_aqui>

{
  "cantidad": 50
}


###
DELETE http://localhost:4001/api/productos/66bbcea52f596d56a7786cb1
Content-Type: application/json
x-auth-token: <tu_token_aqui>
