### Obtener todos los usuarios
GET http://localhost:4000/api/usuarios
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmVkN2I5OThhM2ZmMWU2MTIyMjU5ZiIsImlhdCI6MTcyMzc4MzMyNywiZXhwIjoxNzIzNzg2OTI3fQ.Y-A1I3LmFpxiuqg7_jhvaEoOIJqk9StwKGkpnX1pYCY

###

### Obtener un usuario por ID
GET http://localhost:4000/api/usuarios/66bbc64ec5d07458e5610223
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmVkN2I5OThhM2ZmMWU2MTIyMjU5ZiIsImlhdCI6MTcyMzc4MzMyNywiZXhwIjoxNzIzNzg2OTI3fQ.Y-A1I3LmFpxiuqg7_jhvaEoOIJqk9StwKGkpnX1pYCY

###

### Crear un nuevo usuario
POST http://localhost:4000/api/usuarios
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmVkN2I5OThhM2ZmMWU2MTIyMjU5ZiIsImlhdCI6MTcyMzc4MzMyNywiZXhwIjoxNzIzNzg2OTI3fQ.Y-A1I3LmFpxiuqg7_jhvaEoOIJqk9StwKGkpnX1pYCY

{
  "username": "nuevousasduario",
  "email": "admn@example.com",
  "password": "password123",
  "role": "admin"
}


###

### Actualizar email y role del usuario
PUT http://localhost:4000/api/usuarios/66bbcea52f596d56a7786cb1
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmVkN2I5OThhM2ZmMWU2MTIyMjU5ZiIsImlhdCI6MTcyMzc4MzMyNywiZXhwIjoxNzIzNzg2OTI3fQ.Y-A1I3LmFpxiuqg7_jhvaEoOIJqk9StwKGkpnX1pYCY

{
  "email": "nuevo_email@example.com",
  "role": "user"
}


###

### Actualizar solo la contraseña del usuario
PUT http://localhost:4000/api/usuarios/66bbcea52f596d56a7786cb1/password
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmVkN2I5OThhM2ZmMWU2MTIyMjU5ZiIsImlhdCI6MTcyMzc4MzMyNywiZXhwIjoxNzIzNzg2OTI3fQ.Y-A1I3LmFpxiuqg7_jhvaEoOIJqk9StwKGkpnX1pYCY

{
  "password": "isaiasGMJ"
}


###

### Eliminar un usuario
DELETE http://localhost:4000/api/usuarios/66bbcea52f596d56a7786cb1
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmVkN2I5OThhM2ZmMWU2MTIyMjU5ZiIsImlhdCI6MTcyMzc4MzMyNywiZXhwIjoxNzIzNzg2OTI3fQ.Y-A1I3LmFpxiuqg7_jhvaEoOIJqk9StwKGkpnX1pYCY

###
